name: supaimg-deploy-web
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - apps/supaimg.app/**
      - packages/ui/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
      - run: bun install --frozen-lockfile
      - run: bun run supaimg.app:build
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/supaimg.app/dist --project-name=supaimg
